{
  "type": "record",
  "name": "Envelope",
  "namespace": "thelook.shop.users",
  "fields": [
    {
      "name": "before",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Value",
          "fields": [
            {
              "name": "id",
              "type": "string"
            },
            {
              "name": "first_name",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "last_name",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "email",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "age",
              "type": [
                "null",
                "int"
              ],
              "default": null
            },
            {
              "name": "gender",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "street_address",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "postal_code",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "city",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "state",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "country",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "latitude",
              "type": [
                "null",
                "double"
              ],
              "default": null
            },
            {
              "name": "longitude",
              "type": [
                "null",
                "double"
              ],
              "default": null
            },
            {
              "name": "traffic_source",
              "type": [
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name": "created_at",
              "type": [
                "null",
                {
                  "type": "long",
                  "connect.version": 1,
                  "connect.name": "io.debezium.time.MicroTimestamp"
                }
              ],
              "default": null
            },
            {
              "name": "updated_at",
              "type": [
                "null",
                {
                  "type": "long",
                  "connect.version": 1,
                  "connect.name": "io.debezium.time.MicroTimestamp"
                }
              ],
              "default": null
            }
          ],
          "connect.name": "thelook.shop.users.Value"
        }
      ],
      "default": null
    },
    {
      "name": "after",
      "type": [
        "null",
        "Value"
      ],
      "default": null
    },
    {
      "name": "source",
      "type": {
        "type": "record",
        "name": "Source",
        "namespace": "io.debezium.connector.postgresql",
        "fields": [
          {
            "name": "version",
            "type": "string"
          },
          {
            "name": "connector",
            "type": "string"
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "ts_ms",
            "type": "long"
          },
          {
            "name": "snapshot",
            "type": [
              {
                "type": "string",
                "connect.version": 1,
                "connect.parameters": {
                  "allowed": "true,first,first_in_data_collection,last_in_data_collection,last,false,incremental"
                },
                "connect.default": "false",
                "connect.name": "io.debezium.data.Enum"
              },
              "null"
            ],
            "default": "false"
          },
          {
            "name": "db",
            "type": "string"
          },
          {
            "name": "sequence",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "ts_us",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "ts_ns",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "schema",
            "type": "string"
          },
          {
            "name": "table",
            "type": "string"
          },
          {
            "name": "txId",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "lsn",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "xmin",
            "type": [
              "null",
              "long"
            ],
            "default": null
          },
          {
            "name": "origin",
            "type": [
              "null",
              "string"
            ],
            "default": null
          },
          {
            "name": "origin_lsn",
            "type": [
              "null",
              "long"
            ],
            "default": null
          }
        ],
        "connect.version": 1,
        "connect.name": "io.debezium.connector.postgresql.Source"
      }
    },
    {
      "name": "transaction",
      "type": [
        "null",
        {
          "type": "record",
          "name": "block",
          "namespace": "event",
          "fields": [
            {
              "name": "id",
              "type": "string"
            },
            {
              "name": "total_order",
              "type": "long"
            },
            {
              "name": "data_collection_order",
              "type": "long"
            }
          ],
          "connect.version": 1,
          "connect.name": "event.block"
        }
      ],
      "default": null
    },
    {
      "name": "op",
      "type": "string"
    },
    {
      "name": "ts_ms",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "ts_us",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "ts_ns",
      "type": [
        "null",
        "long"
      ],
      "default": null
    }
  ],
  "connect.version": 2,
  "connect.name": "thelook.shop.users.Envelope"
}